// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/contracts/azure.proto

package contracts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AzureProviderConfig is the typed configuration for the iac.provider module
// provided by workflow-plugin-azure. All fields correspond to the map keys
// accepted by the Initialize(ctx, map[string]any) path.
type AzureProviderConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subscription_id is the Azure subscription ID (required).
	SubscriptionId string `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// resource_group is the default Azure resource group (required).
	ResourceGroup string `protobuf:"bytes,2,opt,name=resource_group,json=resourceGroup,proto3" json:"resource_group,omitempty"`
	// location is the Azure region (default: eastus).
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// storage_account is the Azure Storage account name for Blob operations (optional).
	StorageAccount string `protobuf:"bytes,4,opt,name=storage_account,json=storageAccount,proto3" json:"storage_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AzureProviderConfig) Reset() {
	*x = AzureProviderConfig{}
	mi := &file_internal_contracts_azure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureProviderConfig) ProtoMessage() {}

func (x *AzureProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_contracts_azure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureProviderConfig.ProtoReflect.Descriptor instead.
func (*AzureProviderConfig) Descriptor() ([]byte, []int) {
	return file_internal_contracts_azure_proto_rawDescGZIP(), []int{0}
}

func (x *AzureProviderConfig) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *AzureProviderConfig) GetResourceGroup() string {
	if x != nil {
		return x.ResourceGroup
	}
	return ""
}

func (x *AzureProviderConfig) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AzureProviderConfig) GetStorageAccount() string {
	if x != nil {
		return x.StorageAccount
	}
	return ""
}

var File_internal_contracts_azure_proto protoreflect.FileDescriptor

const file_internal_contracts_azure_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/contracts/azure.proto\x12\x19workflow.plugins.azure.v1\"\xaa\x01\n" +
	"\x13AzureProviderConfig\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12%\n" +
	"\x0eresource_group\x18\x02 \x01(\tR\rresourceGroup\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12'\n" +
	"\x0fstorage_account\x18\x04 \x01(\tR\x0estorageAccountBKZIgithub.com/GoCodeAlone/workflow-plugin-azure/internal/contracts;contractsb\x06proto3"

var (
	file_internal_contracts_azure_proto_rawDescOnce sync.Once
	file_internal_contracts_azure_proto_rawDescData []byte
)

func file_internal_contracts_azure_proto_rawDescGZIP() []byte {
	file_internal_contracts_azure_proto_rawDescOnce.Do(func() {
		file_internal_contracts_azure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_contracts_azure_proto_rawDesc), len(file_internal_contracts_azure_proto_rawDesc)))
	})
	return file_internal_contracts_azure_proto_rawDescData
}

var file_internal_contracts_azure_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_contracts_azure_proto_goTypes = []any{
	(*AzureProviderConfig)(nil), // 0: workflow.plugins.azure.v1.AzureProviderConfig
}
var file_internal_contracts_azure_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_contracts_azure_proto_init() }
func file_internal_contracts_azure_proto_init() {
	if File_internal_contracts_azure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_contracts_azure_proto_rawDesc), len(file_internal_contracts_azure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_contracts_azure_proto_goTypes,
		DependencyIndexes: file_internal_contracts_azure_proto_depIdxs,
		MessageInfos:      file_internal_contracts_azure_proto_msgTypes,
	}.Build()
	File_internal_contracts_azure_proto = out.File
	file_internal_contracts_azure_proto_goTypes = nil
	file_internal_contracts_azure_proto_depIdxs = nil
}
